version: '2.4'
services:
  api:
    container_name: 'sense-test-api'
    image: 'sense-test-api'
    build: .
    command: bash -c "sleep 10 && python3 app.py"
    ports:
      - '6000:6000'
    volumes:
      - ./:/src
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - API_PORT=6000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
  
  postgres:
    container_name: 'sense-test-postgres'
    image: 'postgres:11.1'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./pg-schema.sql:/docker-entrypoint-initdb.d/pg-schema.sql